---

# service_route_id is set in service_delete.yml which calls this task file.
- set_fact:
    matched_route_id: "{{ service_route_id }}"
  when: service_route_id|default(false)

- name: Delete route object associated to kong service object
  uri:
    url:    "{{ kong_admin_api_url|default('http://localhost:8001') }}/routes/{{ matched_route_id }}"
    method: DELETE
    status_code: "204,404"
  register: route_del
  when: matched_route_id != ''
  until: route_del is succeeded
  retries: 10
  delay: 5

#- debug: var=route_del
