---

- debug: msg="Kong Version - {{ kong_version }}"

- name: Check kong version
  fail: msg="Service object requires v0.13+"
  when: kong_version is version_compare('0.13', '<')

- name: Ensure Kong is started
  service:
    name: kong
    state: started

- name: Verify kong admin api available
  uri: 
    url: "{{ kong_admin_api_url|default('http://localhost:8001') }}"
  register: api_available
  until: api_available is succeeded
  retries: 10
  delay: 5

- name: Get list of service objects configured in kong
  uri:
    url: "{{ kong_admin_api_url|default('http://localhost:8001') }}/services"
  register: services
  until: services is succeeded
  retries: 10
  delay: 5

#- debug: var=services

- set_fact: _cmd=add

- set_fact: _cmd=delete
  when: kong_delete_service_obj

- name: Kong Service Object Config
  include_tasks: service_{{ _cmd }}.yml
