---

- name: Validate kong config
  shell: >
      kong check {{ kong_conf_dir }}/kong.conf
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: kong_version is version_compare('0.9.0', '>=')

- name: Reload kong
  service:
    name: kong
    state: reloaded

- name: Restart kong
  service:
    name: kong
    state: restarted
    sleep: 2  # stop race conditions

- name: Reload systemd
  systemd:
    daemon_reload: yes
